name: First workflow

on:
  push:
    branches:
      - "dev"
      - "master"
  workflow_dispatch:
  pull_request_review:
    branches:
      - "master"
    types:
      - "submitted"

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Start jobs 
        run: date
      - name: Run simple command
        run: echo 'Hello DevOps'
      - name: Run another command
        run: echo 'Goodbye'
      - name: Run create file
        run: echo 'File' > file.txt
      - name: Echo file content
        run: cat file.txt
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start jobs
        run: date
      - name: Echo file content
        run: cat file.txt
      - name: Finalized step 
        run: echo 'Job build finished'
    needs: prepare

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Just simple job
        run: echo 'This is just a job'
    needs: build

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Just the simple deployment job
        run: echo 'Deploy code to dev environment'
    needs: prepare
