name: First workflow

on:
  push:
    branches:
      - "dev"
      - "master"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Run simple command
        run: echo 'Hello DevOps'
      - name: Run another command
        run: echo 'Goodbye'
